//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "lastFetchedAt")]
    pub last_fetched_at: Option<DateTimeWithTimeZone>,
    pub username: String,
    #[sea_orm(column_name = "usernameLower")]
    pub username_lower: String,
    pub name: Option<String>,
    #[sea_orm(column_name = "followersCount")]
    pub followers_count: i32,
    #[sea_orm(column_name = "followingCount")]
    pub following_count: i32,
    #[sea_orm(column_name = "notesCount")]
    pub notes_count: i32,
    #[sea_orm(column_name = "avatarId", unique)]
    pub avatar_id: Option<String>,
    #[sea_orm(column_name = "bannerId", unique)]
    pub banner_id: Option<String>,
    pub tags: Vec<String>,
    #[sea_orm(column_name = "isSuspended")]
    pub is_suspended: bool,
    #[sea_orm(column_name = "isSilenced")]
    pub is_silenced: bool,
    #[sea_orm(column_name = "isLocked")]
    pub is_locked: bool,
    #[sea_orm(column_name = "isBot")]
    pub is_bot: bool,
    #[sea_orm(column_name = "isCat")]
    pub is_cat: bool,
    #[sea_orm(column_name = "isAdmin")]
    pub is_admin: bool,
    #[sea_orm(column_name = "isModerator")]
    pub is_moderator: bool,
    pub emojis: Vec<String>,
    pub host: Option<String>,
    pub inbox: Option<String>,
    #[sea_orm(column_name = "sharedInbox")]
    pub shared_inbox: Option<String>,
    pub featured: Option<String>,
    pub uri: Option<String>,
    #[sea_orm(unique)]
    pub token: Option<String>,
    #[sea_orm(column_name = "isExplorable")]
    pub is_explorable: bool,
    #[sea_orm(column_name = "followersUri")]
    pub followers_uri: Option<String>,
    #[sea_orm(column_name = "lastActiveDate")]
    pub last_active_date: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "hideOnlineStatus")]
    pub hide_online_status: bool,
    #[sea_orm(column_name = "isDeleted")]
    pub is_deleted: bool,
    #[sea_orm(column_name = "driveCapacityOverrideMb")]
    pub drive_capacity_override_mb: Option<i32>,
    #[sea_orm(column_name = "movedToUri")]
    pub moved_to_uri: Option<String>,
    #[sea_orm(column_name = "alsoKnownAs", column_type = "Text", nullable)]
    pub also_known_as: Option<String>,
    #[sea_orm(column_name = "speakAsCat")]
    pub speak_as_cat: bool,
    #[sea_orm(column_name = "isIndexable")]
    pub is_indexable: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
